CONTIKI_PROJECT = hc-sr04
CONTIKI = ../../..

PLATFORMS_ONLY += openmote

include $(CONTIKI)/Makefile.identify-target

MODULES_REL += $(TARGET)

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
